import { Employee } from "@/types/employee";

export const EMPLOYEES: Employee[] = [
  {
    id: 'marcus',
    initials: 'MR',
    avatarColor: '#1E4D7A',
    name: 'Marcus R.',
    title: 'Cashier',
    meta: '4 issues tracked · 3 resolved · 1 in progress · 0 stalled',
    badge: 'resolved',
    winRate: '75%',
    avgWks: '2.1',
    stalledCount: '0',
    winRateColor: 'good',
    avgWksColor: 'neutral',
    stalledColor: 'good',
    issues: [
      {
        id: 'marcus-1',
        category: 'hospitality',
        description: 'Greeting delay averaging 9s — target 5s',
        coaching: 'Coach: "Make eye contact within 2s of approach"',
        scoreBefore: 72,
        scoreAfter: 88,
        scoreDelta: 16,
        scoreDeltaType: 'up',
        weeksLabel: '3 wks',
        pips: ['filled-green', 'filled-green', 'filled-green'],
        status: 'resolved',
      },
      {
        id: 'marcus-2',
        category: 'hospitality',
        description: 'Send-off phrase missing in 60% of transactions',
        coaching: 'Coach: "Close every transaction with a thank-you phrase"',
        scoreBefore: 78,
        scoreAfter: 85,
        scoreDelta: 7,
        scoreDeltaType: 'up',
        weeksLabel: '2 wks',
        pips: ['filled-green', 'filled-green'],
        status: 'resolved',
      },
      {
        id: 'marcus-3',
        category: 'tone',
        description: 'Tone flag during back-to-back rush transactions',
        coaching: 'Coach: "One breath reset between customers during peak"',
        scoreBefore: 80,
        scoreAfter: 88,
        scoreDelta: 8,
        scoreDeltaType: 'up',
        weeksLabel: '2 wks',
        pips: ['filled-green', 'filled-green'],
        status: 'resolved',
      },
      {
        id: 'marcus-4',
        category: 'checkout',
        description: 'Checkout slows after item #5 — bagging rhythm',
        coaching: 'Coach: "Batch items before scanning to cut 8–12s"',
        scoreBefore: 74,
        scoreAfter: 74,
        scoreDelta: 0,
        scoreDeltaType: 'flat',
        weeksLabel: '1 wk',
        pips: ['filled-amber', 'empty', 'empty'],
        status: 'progress',
      },
    ],
    effBars: [
      { label: 'Hospitality coaching', pct: '100% resolved', fillWidth: '100%', fillColor: 'var(--color-accent)' },
      { label: 'Tone coaching', pct: '100% resolved', fillWidth: '100%', fillColor: 'var(--color-accent)' },
      { label: 'Checkout coaching', pct: '0% — 1 wk in', fillWidth: '10%', fillColor: 'var(--color-amber)' },
    ],
    circleStroke: '#1D5C3A',
    circleDasharray: '150.8',
    circleDashoffset: '37.7',
  },
  {
    id: 'tara',
    initials: 'TC',
    avatarColor: '#1D5C3A',
    name: 'Tara C.',
    title: 'Manager',
    meta: '2 issues tracked · 2 resolved · 0 in progress · 0 stalled',
    badge: 'good',
    winRate: '100%',
    avgWks: '1.5',
    stalledCount: '0',
    winRateColor: 'good',
    avgWksColor: 'neutral',
    stalledColor: 'good',
    issues: [
      {
        id: 'tara-1',
        category: 'checkout',
        description: 'Checkout speed over 35s during rush periods',
        coaching: 'Coach: "Pre-stage bags before customer approaches"',
        scoreBefore: 76,
        scoreAfter: 88,
        scoreDelta: 12,
        scoreDeltaType: 'up',
        weeksLabel: '2 wks',
        pips: ['filled-green', 'filled-green'],
        status: 'resolved',
      },
      {
        id: 'tara-2',
        category: 'tone',
        description: 'Tone score dipped below 80 for 2 consecutive shifts',
        coaching: 'Coach: "Pause and reset before difficult interactions"',
        scoreBefore: 78,
        scoreAfter: 95,
        scoreDelta: 17,
        scoreDeltaType: 'up',
        weeksLabel: '1 wk',
        pips: ['filled-green'],
        status: 'resolved',
      },
    ],
    effBars: [
      { label: 'Checkout coaching', pct: '100% resolved', fillWidth: '100%', fillColor: 'var(--color-accent)' },
      { label: 'Tone coaching', pct: '100% resolved', fillWidth: '100%', fillColor: 'var(--color-accent)' },
    ],
    circleStroke: '#1D5C3A',
    circleDasharray: '201.1',
    circleDashoffset: '0',
  },
  {
    id: 'jamie',
    initials: 'JL',
    avatarColor: '#B8622A',
    name: 'Jamie L.',
    title: 'Stock Associate',
    meta: '4 issues tracked · 1 resolved · 1 in progress · 2 stalled 🚨',
    badge: 'stalled',
    winRate: '25%',
    avgWks: '3.8',
    stalledCount: '2',
    winRateColor: 'bad',
    avgWksColor: 'ok',
    stalledColor: 'bad',
    issues: [
      {
        id: 'jamie-1',
        category: 'hospitality',
        description: 'Counter left unattended during shift',
        coaching: 'Coach: "Set a 10-min timer to return to counter"',
        scoreBefore: 71,
        scoreAfter: 80,
        scoreDelta: 9,
        scoreDeltaType: 'up',
        weeksLabel: '2 wks',
        pips: ['filled-green', 'filled-green'],
        status: 'resolved',
      },
      {
        id: 'jamie-2',
        category: 'checkout',
        description: 'Checkout speed declining — 3rd consecutive week',
        coaching: 'Coach: "Batch items before scanning" — no response after 3 wks',
        scoreBefore: 66,
        scoreAfter: 58,
        scoreDelta: -8,
        scoreDeltaType: 'down',
        weeksLabel: '3 wks',
        pips: ['filled-red', 'filled-red', 'filled-red'],
        status: 'stalled',
        stalled: true,
      },
      {
        id: 'jamie-3',
        category: 'hospitality',
        description: 'Greeting rate below 80% threshold',
        coaching: 'Coach: "Eye contact within 2s" — minimal movement after 3 wks',
        scoreBefore: 77,
        scoreAfter: 68,
        scoreDelta: -9,
        scoreDeltaType: 'down',
        weeksLabel: '3 wks',
        pips: ['filled-red', 'filled-red', 'filled-red'],
        status: 'stalled',
        stalled: true,
      },
      {
        id: 'jamie-4',
        category: 'tone',
        description: 'Tone flags during 12–2p peak rush',
        coaching: 'Coach: "Slow breath before each new customer at peak"',
        scoreBefore: 71,
        scoreAfter: 71,
        scoreDelta: 0,
        scoreDeltaType: 'flat',
        weeksLabel: '1 wk',
        pips: ['filled-amber', 'empty', 'empty'],
        status: 'progress',
      },
    ],
    effBars: [
      { label: 'Hospitality coaching', pct: '50% — 1 stalled', fillWidth: '50%', fillColor: 'var(--color-amber)' },
      { label: 'Checkout coaching', pct: '0% — stalled 3 wks', fillWidth: '5%', fillColor: 'var(--color-danger)' },
      { label: 'Tone coaching', pct: 'Too early to tell', fillWidth: '15%', fillColor: 'var(--color-border)' },
    ],
    circleStroke: '#B52B1E',
    circleDasharray: '201.1',
    circleDashoffset: '150.8',
    circleValueColor: 'var(--color-danger)',
  },
  {
    id: 'sofia',
    initials: 'SK',
    avatarColor: '#555',
    name: 'Sofia K.',
    title: 'Cashier',
    meta: '3 issues tracked · 1 resolved · 1 in progress · 1 stalled',
    badge: 'progress',
    winRate: '33%',
    avgWks: '2.7',
    stalledCount: '1',
    winRateColor: 'ok',
    avgWksColor: 'neutral',
    stalledColor: 'ok',
    issues: [
      {
        id: 'sofia-1',
        category: 'checkout',
        description: 'Checkout speed consistently over 50s',
        coaching: 'Coach: "Scan while customer bags to reduce wait"',
        scoreBefore: 54,
        scoreAfter: 66,
        scoreDelta: 12,
        scoreDeltaType: 'up',
        weeksLabel: '3 wks',
        pips: ['filled-green', 'filled-green', 'filled-green'],
        status: 'resolved',
      },
      {
        id: 'sofia-2',
        category: 'hospitality',
        description: 'Greeting delay averaging 11s — target 5s',
        coaching: 'Coach: "Eye contact within 2s of approach"',
        scoreBefore: 58,
        scoreAfter: 63,
        scoreDelta: 5,
        scoreDeltaType: 'up',
        weeksLabel: '2 wks',
        pips: ['filled-amber', 'filled-amber', 'empty'],
        status: 'progress',
      },
      {
        id: 'sofia-3',
        category: 'hospitality',
        description: 'Low engagement — no eye contact or name use',
        coaching: 'Coach: "Use customer name once per transaction" — no change 3 wks',
        scoreBefore: 62,
        scoreAfter: 63,
        scoreDelta: 1,
        scoreDeltaType: 'flat',
        weeksLabel: '3 wks',
        pips: ['filled-red', 'filled-red', 'filled-red'],
        status: 'stalled',
        stalled: true,
      },
    ],
    effBars: [
      { label: 'Checkout coaching', pct: '100% resolved', fillWidth: '100%', fillColor: 'var(--color-accent)' },
      { label: 'Hospitality coaching', pct: '0% — 1 stalled', fillWidth: '10%', fillColor: 'var(--color-danger)' },
    ],
    circleStroke: '#C47F18',
    circleDasharray: '201.1',
    circleDashoffset: '134.1',
    circleValueColor: 'var(--color-amber)',
  },
  {
    id: 'devon',
    initials: 'DW',
    avatarColor: '#7A6A55',
    name: 'Devon W.',
    title: 'Cashier',
    meta: '3 issues tracked · 2 resolved · 1 in progress · 0 stalled',
    badge: 'progress',
    winRate: '67%',
    avgWks: '2.0',
    stalledCount: '0',
    winRateColor: 'good',
    avgWksColor: 'neutral',
    stalledColor: 'good',
    issues: [
      {
        id: 'devon-1',
        category: 'hospitality',
        description: 'No handoff detected in 40% of transactions',
        coaching: 'Coach: "Always direct customer to next step before closing"',
        scoreBefore: 68,
        scoreAfter: 80,
        scoreDelta: 12,
        scoreDeltaType: 'up',
        weeksLabel: '2 wks',
        pips: ['filled-green', 'filled-green'],
        status: 'resolved',
      },
      {
        id: 'devon-2',
        category: 'time',
        description: 'Greeting delay spiking during 5–7p shift end',
        coaching: 'Coach: "Stay engaged last 90 mins — fatigue watch"',
        scoreBefore: 74,
        scoreAfter: 82,
        scoreDelta: 8,
        scoreDeltaType: 'up',
        weeksLabel: '2 wks',
        pips: ['filled-green', 'filled-green'],
        status: 'resolved',
      },
      {
        id: 'devon-3',
        category: 'checkout',
        description: 'Checkout speed inconsistent — wide variance shift to shift',
        coaching: 'Coach: "Standardize scanning sequence every transaction"',
        scoreBefore: 74,
        scoreAfter: 78,
        scoreDelta: 4,
        scoreDeltaType: 'up',
        weeksLabel: '1 wk',
        pips: ['filled-amber', 'empty', 'empty'],
        status: 'progress',
      },
    ],
    effBars: [
      { label: 'Hospitality coaching', pct: '100% resolved', fillWidth: '100%', fillColor: 'var(--color-accent)' },
      { label: 'Time to Service coaching', pct: '100% resolved', fillWidth: '100%', fillColor: 'var(--color-accent)' },
      { label: 'Checkout coaching', pct: 'In progress — 1 wk', fillWidth: '25%', fillColor: 'var(--color-amber)' },
    ],
    circleStroke: '#1D5C3A',
    circleDasharray: '201.1',
    circleDashoffset: '66.4',
  },
]
