import type { ApiManager } from '@/types/manager'

// Seed data for the (still-mocked) Manager Management page. `store_ids` values
// line up with the `_id`s in `STORES` (src/lib/store-data.ts).
export const MANAGERS: ApiManager[] = [
  {
    _id: 'mgr_0001',
    user_id: 'MGR-1024',
    first_name: 'Priya',
    last_name: 'Nair',
    email: 'priya.nair@example.com',
    phone: '+1 555 0142',
    role_name: 'manager',
    store_ids: ['69c19e66a27efce5858b6487', 'STORE-001'],
    is_active: true,
    must_change_password: false,
  },
  {
    _id: 'mgr_0002',
    user_id: 'MGR-1025',
    first_name: 'Marcus',
    last_name: 'Reed',
    email: 'marcus.reed@example.com',
    phone: '+1 555 0187',
    role_name: 'manager',
    store_ids: ['STORE-002'],
    is_active: true,
    must_change_password: true,
  },
  {
    _id: 'mgr_0003',
    user_id: 'MGR-1026',
    first_name: 'Elena',
    last_name: 'Vasquez',
    email: 'elena.vasquez@example.com',
    phone: null,
    role_name: 'manager',
    store_ids: ['STORE-003', 'STORE-101', 'STORE-102'],
    is_active: true,
    must_change_password: false,
  },
  {
    _id: 'mgr_0004',
    user_id: 'MGR-1027',
    first_name: 'David',
    last_name: 'Okafor',
    email: 'david.okafor@example.com',
    phone: '+1 555 0203',
    role_name: 'manager',
    store_ids: ['STORE-101'],
    is_active: false,
    must_change_password: false,
  },
  {
    _id: 'mgr_0005',
    user_id: 'MGR-1028',
    first_name: 'Hannah',
    last_name: 'Brooks',
    email: 'hannah.brooks@example.com',
    phone: '+1 555 0219',
    role_name: 'manager',
    store_ids: ['STORE-001', 'STORE-002'],
    is_active: true,
    must_change_password: true,
  },
  {
    _id: 'mgr_0006',
    user_id: 'MGR-1029',
    first_name: 'Tomás',
    last_name: 'Herrera',
    email: 'tomas.herrera@example.com',
    phone: null,
    role_name: 'manager',
    store_ids: ['STORE-102'],
    is_active: true,
    must_change_password: false,
  },
  {
    _id: 'mgr_0007',
    user_id: 'MGR-1030',
    first_name: 'Aisha',
    last_name: 'Khan',
    email: 'aisha.khan@example.com',
    phone: '+1 555 0244',
    role_name: 'manager',
    store_ids: ['69c19e66a27efce5858b6487'],
    is_active: true,
    must_change_password: false,
  },
]

// Managers that start out archived (visible only on the Archived tab).
export const ARCHIVED_MANAGERS: ApiManager[] = [
  {
    _id: 'mgr_9001',
    user_id: 'MGR-0912',
    first_name: 'Gerald',
    last_name: 'Simms',
    email: 'gerald.simms@example.com',
    phone: '+1 555 0101',
    role_name: 'manager',
    store_ids: ['STORE-003'],
    is_active: false,
    must_change_password: false,
    archived_by: 'owner@demo.com',
    archived_at: '2026-06-18T14:32:00Z',
  },
  {
    _id: 'mgr_9002',
    user_id: 'MGR-0888',
    first_name: 'Rachel',
    last_name: 'Lindqvist',
    email: 'rachel.lindqvist@example.com',
    phone: null,
    role_name: 'manager',
    store_ids: ['STORE-101', 'STORE-102'],
    is_active: false,
    must_change_password: false,
    archived_by: 'owner@demo.com',
    archived_at: '2026-04-02T09:05:00Z',
  },
]
