import type { SwagOrder, SwagStoreConfig } from "@/types/swagstore";

export const SWAG_STORE: SwagStoreConfig = {
    title: 'Swag Store',
    subtitle: 'Redeem your points for rewards',
    earnRateText: 'You earn **~120 pts/shift** at your current score level. Higher score = more points per shift.',
    catalog: [
        {
            id: 'coffee',
            emoji: '☕',
            name: 'Free Coffee — Any Size',
            desc: 'Redeem at the register anytime during your shift',
            cost: 250,
            category: 'Food & Drink',
            status: 'active',
            stock: null, // Unlimited
            createdAt: '2026-06-01T08:00:00.000Z',
        },
        {
            id: 'tshirt',
            emoji: '🎽',
            name: 'Pythia Team T-Shirt',
            desc: 'Limited edition — only for top performers',
            cost: 800,
            category: 'Apparel',
            status: 'active',
            stock: 14,
            createdAt: '2026-06-01T08:00:00.000Z',
        },
        {
            id: 'gift10',
            emoji: '🎟️',
            name: '$10 Store Voucher',
            desc: 'Store voucher — use on anything in the store',
            cost: 1000,
            category: 'Gift Cards',
            status: 'active',
            stock: 25,
            createdAt: '2026-06-01T08:00:00.000Z',
        },
        {
            id: 'cap',
            emoji: '🧢',
            name: 'Pythia Cap',
            desc: 'Embroidered logo cap — show off your rank',
            cost: 600,
            category: 'Apparel',
            status: 'active',
            stock: 20,
            createdAt: '2026-06-01T08:00:00.000Z',
        },
        {
            id: 'halfday',
            emoji: '🏖️',
            name: 'Half Day Off',
            desc: 'Redeem for a 4-hour shift reduction — manager approved',
            cost: 2000,
            category: 'Perks',
            status: 'active',
            stock: 5,
            createdAt: '2026-06-01T08:00:00.000Z',
        },
        {
            id: 'gift25',
            emoji: '🎮',
            name: 'Gaming / Digital Voucher',
            desc: 'Digital delivery within 24 hours of redemption',
            cost: 2500,
            category: 'Gift Cards',
            status: 'active',
            stock: 10,
            createdAt: '2026-06-01T08:00:00.000Z',
        },
    ],
}

export const INITIAL_SWAG_ORDERS: SwagOrder[] = [
    {
        id: 'ord_101',
        productId: 'tshirt',
        productName: 'Pythia Team T-Shirt',
        productEmoji: '🎽',
        category: 'Apparel',
        employeeId: 'emp_marcus',
        employeeName: 'Marcus Reynolds',
        pointsCost: 800,
        status: 'pending',
        orderedAt: '2026-06-12T14:30:00.000Z',
    },
    {
        id: 'ord_102',
        productId: 'coffee',
        productName: 'Free Coffee — Any Size',
        productEmoji: '☕',
        category: 'Food & Drink',
        employeeId: 'emp_sarah',
        employeeName: 'Sarah Chen',
        pointsCost: 250,
        status: 'completed',
        orderedAt: '2026-06-10T09:15:00.000Z',
        completedAt: '2026-06-10T09:20:00.000Z',
        fulfilledBy: 'Jamie L. (Manager)',
    },
    {
        id: 'ord_103',
        productId: 'gift10',
        productName: '$10 Store Voucher',
        productEmoji: '🎟️',
        category: 'Gift Cards',
        employeeId: 'emp_alex',
        employeeName: 'Alex Rivera',
        pointsCost: 1000,
        status: 'completed',
        orderedAt: '2026-06-08T16:45:00.000Z',
        completedAt: '2026-06-09T11:00:00.000Z',
        fulfilledBy: 'Jamie L. (Manager)',
    },
]

