// Endpoints served by the data service (dataClient)
export const PYTHIA_2_API = {
  auth: {
    login: '/auth/login',
    loginTenant: '/auth/tenant-login',
    refresh: '/auth/refresh',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    p1Profile: '/profile/',
  },
  dashboard: {
    summary: '/dashboard/summary',
    shiftSummaryHighlights: '/dashboard/shift-summary/highlights',
  },
  demographics: {
    ageDistribution: '/demographics/age-distribution',
    genderDistribution: '/demographics/gender-distribution',
    customerSegments: '/demographics/customer-segments',
  },
  benchmarking: {
    allStoreData: '/benchmarking/all_store_data',
    networkIntelligence: '/benchmarking/network_intelligence',
  },
  roi: {
    attribution: '/roi/attribution',
    shareWithInvestor: '/roi/attribution/share',
  },
  coaching: {
    moments: '/coaching-moments',
  },
  employees: {
    list: '/employees',
    create: '/employees',
    archived: '/employees/archived',
    detail: (userId: string) => `/employees/${userId}`,
    credentials: (userId: string) => `/employees/${userId}/credentials`,
    archive: (userId: string) => `/employees/${userId}/archive`,
    unarchive: (userId: string) => `/employees/${userId}/unarchive`,
  },
  unknownIdentities: {
    list: '/unknown-identities',
    count: '/unknown-identities/count',
    trashed: '/unknown-identities/trashed',
    assign: (identityId: string) => `/unknown-identities/${identityId}/assign`,
    trash: (identityId: string) => `/unknown-identities/${identityId}/trash`,
    restore: (identityId: string) => `/unknown-identities/${identityId}/restore`,
  },
  videoIdentities: {
    list: '/video-identities',
    stats: '/video-identities/stats',
    presign: '/video-identities/presign',
  },
  managerCoaching: {
    signals: '/manager-coaching/signals',
    signal: (planId: string) => `/manager-coaching/signals/${planId}`,
    summary: '/manager-coaching/summary',
    effectiveness: '/manager-coaching/effectiveness',
    employees: '/manager-coaching/employees',
    employeeDetail: (userId: string) => `/manager-coaching/employees/${userId}`,
  },
  managerDashboard: {
    summary: '/manager-dashboard/summary',
    leaderboard: '/manager-dashboard/leaderboard',
    trend: '/manager-dashboard/trend',
  },
  superAdmin: {
    fieldConfig: '/super-admin/field-config',
    fieldConfigForRole: (roleName: string) => `/super-admin/field-config/${roleName}`,
    demos: '/super-admin/demos',
    manualSend: '/super-admin/manual-send',
    bulkTrigger: '/super-admin/bulk-trigger',
    sentStatus: '/super-admin/sent-status',
  },
  deviceHealth: {
    list: '/device-states',
    detail: (deviceId: string) => `/device-states/${deviceId}`,
    ws: '/device-states/ws',
  },
  staffing: {
    schedule: '/staffing/schedule',
    scheduleGenerate: '/staffing/schedule/generate',
    scheduleEntry: (shiftId: string) => `/staffing/schedule/${shiftId}`,
    schedulePublish: '/staffing/schedule/publish',
    roster: '/staffing/roster',
    trafficHeatmap: '/staffing/traffic-heatmap',
    insights: '/staffing/insights',
    recommendations: '/staffing/recommendations',
    recommendationsGenerate: '/staffing/recommendations/generate',
    recommendationApply: (id: string) => `/staffing/recommendations/${id}/apply`,
    recommendationDismiss: (id: string) => `/staffing/recommendations/${id}/dismiss`,
  },
  tenants: {
    list: '/super-admin/tenants',
    create: '/super-admin/tenants',
    detail: (id: string) => `/super-admin/tenants/${id}`,
    updateStatus: (id: string) => `/super-admin/tenants/${id}/status`,
    status: (id: string) => `/super-admin/tenants/${id}/status`,
    checklist: (id: string) => `/super-admin/tenants/${id}/checklist`,
  },
  stores: {
    list: '/stores',
    detail: (id: string) => `/stores/${id}`,
    create: '/stores',
    bulkCreate: '/stores/bulk',
    pairingCode: (id: string) => `/stores/${id}/pairing-code`,
    heartbeat: (id: string) => `/stores/${id}/heartbeat`,
    simulateHeartbeat: (id: string) => `/stores/${id}/heartbeat`,
    updateStatus: (id: string) => `/stores/${id}/status`,
  },
  owners: {
    list: '/super-admin/owners',
    create: '/super-admin/owners',
    archived: '/super-admin/owners/archived',
    detail: (userId: string) => `/super-admin/owners/${userId}`,
    credentials: (userId: string) => `/super-admin/owners/${userId}/credentials`,
    archive: (userId: string) => `/super-admin/owners/${userId}/archive`,
    unarchive: (userId: string) => `/super-admin/owners/${userId}/unarchive`,
  },
  onboarding: {
    wizardState: (tenantId: string) => `/super-admin/onboarding/${tenantId}`,
    stepUpdate: (tenantId: string) => `/super-admin/onboarding/${tenantId}/step`,
    complete: (tenantId: string) => `/super-admin/onboarding/${tenantId}/complete`,
  },
} as const
